### ISSUE TITLE
Cannot use web scraper more than once in a session

### ISSUE THREAD

**Issue by Kranium2002** [kshitijagrwl/chat-with-docs#5]
**Issue Title:** Cannot use web scraper more than once in a session

**Description:**

**Error:**
```
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/d/Projects/chat-with-docs/venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  ... (rest of the traceback)
  File "/mnt/d/Projects/chat-with-docs/venv/lib/python3.10/site-packages/twisted/internet/base.py", line 843, in startRunning
    raise error.ReactorNotRestartable()
twisted.internet.error.ReactorNotRestartable
```

**Environment:**
- Python Version: 3.10.12
- Operating System: [Windows]

**Expected Behavior:** 
Web scraper should run again on the specified url and give the json file for links of the documentation.

**Actual Behavior:** 
Scrapy web scraper gives error and to get to work again I have to restart the server. The error has been mentioned above.

**Steps to Reproduce:**
1. Start the server by running server.py file.
2. Make 2 consecutive requests on /getLinks with any url.

**Comment by kshitijagrwl** [comment]
Can use this to bypass errors caused by `twisted` https://github.com/itamarst/crochet

**Comment by knofte** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @somnek, @adriaan, @melvin0008, @namuwikilover, @shibasisp, @NateDogDotNet, @skollcaku, @pladaria, @stan-devproject, @ammarm08, @rinn7e, @naveensrinivasan, @sujaykundu777, @Vanilladelphia, @Sayrarh, @adrianmoses, @edachow, @ResourceHog, @erlenstar, @MostafaMhmod, @valpackett, @chptx, @tariqdude, @lxhelili, @abhinavchanda, @tolgaergin, @siddhanjay, @bolak, @sekl, @rootulp, @sebastianlzy, @rudehn, @peterborodatyy, @kotAPI, @foopang, @Dadybayo, @shafu0x, @BartoszJarocki, @VishalRohra, @taylorlee, @ckanthony, @atyenoria, @dogecrypto, @chelleshocked, @agorf, @vietdien2005, @angadp, @blokboy, @txgo, @guilhermevpinto

**Comment by kotAPI** [comment]
Instagram, Facebook, YouTube, now we got spammers on GitHub too?

**Comment by ckanthony** [comment]
Unfortunately it seems to be like so now.  Some of my repo got this too, and they randomly tagging some others.  Even if we don’t know each other, I would take this chance to wish everybody a happy new year.  Don’t click on that scam link btw

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
